services:
#  ingestion:
#     image: docker.elastic.co/logstash/logstash:9.2.0
#     environment:
#       XPACK_MONITORING_ENABLED: "false"
#     volumes:
#       - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#       - super-cash-stream_data:/data
#     depends_on:
#       topics:
#         condition: service_completed_successfully
  ingestion:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - super-cash-stream_data:/data:ro
    command: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
    depends_on:
      topics:
        condition: service_completed_successfully
  broker:
    image: apache/kafka:4.1.0
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    healthcheck:
      test: ["CMD", "bash", "-c", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5

  topics:
    image: apache/kafka:4.1.0
    command: >
      bash -c "
      echo '⏳ Waiting for Kafka...';
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:9092 --list;
      echo '✅ Creating topics...';
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic cashflow --bootstrap-server broker:9092;
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic cashanalytics --bootstrap-server broker:9092"
    depends_on:
      broker:
        condition: service_healthy

  stream:
    build:
      context: ./stream
      dockerfile: src/main/java/supercashstream/Dockerfile.stream
    container_name: supercash-stream
    depends_on:
      broker:
        condition: service_started
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:9092
    restart: unless-stopped

  producer:
    build:
      context: ./stream
      dockerfile: src/main/java/supercashstream/Dockerfile.producer
    container_name: supercash-producer
    depends_on:
      broker:
        condition: service_started
    environment:
      - BOOTSTRAP_SERVERS=broker:9092
    restart: unless-stopped

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.29.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "broker:9092"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.29.0
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
volumes:
  super-cash-stream_data:
